# Generated by Django 6.0 on 2025-12-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doogsan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripbooking',
            unique_together=set(),
        ),
    ]
