# Generated by Django 6.0 on 2025-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doogsan_app', '0002_alter_tripbooking_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='acct_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booked_balance',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cleared_balance',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cust_memo_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cust_memo_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cust_memo_line3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='event_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='narration',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_ref',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='posting_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
